### ISSUE TITLE
Index out of bounds error when running project 

### ISSUE THREAD

**Issue by ghost** [NicoHood/guestwlan#1]
Traceback (most recent call last):
   File "/usr/share/guestwlan/guestwlan.py", line 160, in <module>
     GuestWLANApp().run()
   File "/usr/lib/python3.6/site-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "/usr/share/guestwlan/guestwlan.py", line 143, in build
     SlideShow.update()
   File "/usr/share/guestwlan/guestwlan.py", line 75, in update
     self.slide.source = self.filename[self.i]

**Comment by NicoHood** [comment]
Did you add some photos already?
Which OS do you use?
Do your photos have special UTF8 characters?

**Comment by ghost** [comment]
Arch linux. I would like to disable the slideshow. I took a quick look at the code and all i saw was it setting the directory but no option to just disable it

**Comment by NicoHood** [comment]
You do not need to start the service. Just start the qrgen service and the ap service.

**Comment by ghost** [comment]
Id like the service that displays the QR code but just that no need for pictures. I would normally just start guestwlan.py, am i supposed to not use that script then?

**Comment by NicoHood** [comment]
You are supposed to run the service, not the script directly (at least as productive run).
You can just ignore the slideshow then. I guess it gives this error if no pictures were used. I need to disable the slideshow then. Feel free to fix it, I currently have no time to do so. 

As a workaround You can try to add a single picture as slideshow.

**Comment by ghost** [comment]
alright what part of your code handles the slideshow, ill try to just eliminate sections

**Comment by NicoHood** [comment]
Just remove the slideshow stuff in the .py and .kv file. Its quite simple:
https://github.com/NicoHood/guestwlan/blob/master/guestwlan.py
https://github.com/NicoHood/guestwlan/blob/master/guestwlan.kv

A proper fix would be better though. But I also have little knowledge about kivy how to properly disablet he back button.
